# -*- python -*-
############################
## load the config

## use the environment set in the top-level
## SConstruct file

Import( '*' )
myenv=env.Copy()
Import("soundLibs")

rgseqSources = Split("""
mmappedcontrolblock.cpp
mmappedsegment.cpp
rosegardensequencer.cpp
main.cpp
sequencermapper.cpp
rosegardensequenceriface.skel
""")

rgseq = KDEprogram('rosegardensequencer', rgseqSources, myenv)

KDEaddpaths( ['../base', '../sound', '../gui', '../', './'], myenv)
KDEaddlibs(['RosegardenSequencer', 'RosegardenSound', 'base', 'kdeui', 'kdecore'], myenv)

myenv['LIBPATH'].insert(0, '../base')
myenv['LIBPATH'].insert(0, '../sound')

for dep in soundLibs:
    Depends(rgseq, dep)

