#!/bin/sh

unset CDPATH

SRCDIR=$HOME/rosegarden

cd $SRCDIR

VERSION=`grep INIT_AUTOMAKE configure.in.in | cut -d ',' -f2 | tr -d ')'`

echo "VERSION = $VERSION"

DESTDIR=$HOME/tmp/rosegarden-$VERSION

rm -rf $DESTDIR

echo "Copying files..."
cp -R $SRCDIR $DESTDIR

cd $DESTDIR || exit -1

echo "Building distrib..."
make distclean && sh ./rb_configure && make dist

