#!/bin/bash

# ANSI_defs
#
# Universal functions used by many of Silvan's scripts
#
# D. Michael McIntyre/Silvan <silvan@windows-sucks.com>

# color definitions...  I like color...

GRY="\e[0m"         # compatability with old scripts (actually reset, not gray)
RST=$GRY			# reset to user norm
RED="\e[0;31;1m"	# bold red
BLU="\e[0;34;1m"	# bold blue
GRN="\e[0;32;1m"	# bold green
CYN="\e[0;36;1m"	# bold cyan
YEL="\e[0;33;1m"	# bold yellow
MAG="\e[0;35;1m"	# bold magenta
WHT="\e[0;1m"		# bold white

red="\e[0;31m"		# red
blu="\e[0;34m"		# blue
grn="\e[0;32m"		# green
cyn="\e[0;36m"		# cyan
yel="\e[0;33m"		# yellow/brown
mag="\e[0;35m"		# magenta


# since bash doesn't have access to $COLUMNS unless user happens to have
# exported it (as far as I can tell) then rip off the following code
# snippets from LFS init scripts

if [ -z "$COLUMNS" ]
then
	[ -x /usr/bin/tty ] && CONSOLE=`/usr/bin/tty`
	[ -z "$CONSOLE" ] && CONSOLE=/dev/console
	SIZE=$(stty size < $CONSOLE)
	COLUMNS=${SIZE#*\ }
fi

# set our column position for status feedback messages
(( COL = COLUMNS - 10 ))

# set the ANSI code to move the cursor to said position
MOV="\e[${COL}G"

Failed (){
	printf "$MOV$RED[FAILED]\n$RST"
}

OK () {
	printf "$MOV$GRN[  OK  ]\n$RST"
}
