#!/bin/bash
#
# startrg
#
# D. Michael McIntyre <dmmcintyr@users.sourceforge.net>
#
# This script is a convenient way to start Rosegarden with the output from
# iiwusynth and jackd in separate xterms, and the KDE_DEBUG environment
# variable set so that KDE's crash handler is disabled.  Of course your needs
# and requirements will vary, and this script in present form isn't very
# flexible.  You'll need to edit the USER VARIABLES below to configure its
# execution, and possibly edit the guts of the script itself.

# USER VARIABLES
#
# TOGGLES

start_jack=false  # jack isn't currently working for me
start_iiwusynth=true
log_to_xterm=true

#
# COMMAND USED TO START THE JACK SERVER
jack_command="jackd -v -d alsa -d hw:0"

#
# SOUNDFONT TO USE WITH IIWUSYNTH
soundfont="$HOME/data/soundfonts/4GMGSMT.SF2"

# COMMAND USED TO START IIWUSYNTH
ii_command="iiwusynth -m alsa_seq $soundfont"

#
# FONT TO USE FOR XTERM (USE xfontsel TO GENERATE THE STRING)
font="*-fixed-*-*-20-*-*-*-*-*-*-*"

#
# Used to log program output to a dedicated Xterm
#
Xterm () {
    /usr/X11R6/bin/xterm -fn "$1"                     \
        -geometry 80x25 -w 1 -T "$2"                  \
        +ah -bc -b 0 -pc -cn +mb -mesg +sb +sf +vb  \
                -fg white -bg black -e "$3" &
}

Wait () {
    printf "Waiting on $1 to come up..."
    until (pgrep $1 > /dev/null 2>&1); do
        printf "."
        sleep 1
    done
    echo
}
                
# Disable the KDE crash handler
export KDE_DEBUG=1

# Start jackd
if [ "$start_jack" == "true" ]; then
    echo Starting jackd...
    if [ "$log_to_xterm" == "true" ]; then
        Xterm $font "jackd status" $jack_command
    else
        $jack_command > /dev/null 2>&1 &
    fi
    Wait jackd
else
    echo Skipping jackd...
fi

# Start IIWU Synth
if [ "$start_iiwusynth" == "true" ]; then
    echo Starting iiwusynth...
    if [ "$log_to_xterm" == "true" ]; then
        Xterm $font "iiwusynth status" $ii_command
    else
        $ii_command > /dev/null 2>&1  &
    fi
    Wait iiwusynth
else
    echo Skipping iiwusynth...
fi

# Start Rosegarden
echo Starting Rosegarden...
if [ "$log_to_xterm" == "true" ]; then
    Xterm $font "rosegarden status" rosegarden
else
    rosegarden &
fi
