#! /usr/bin/env python

# -*- python -*-
############################
## load the config

## use the myenv.ronment set in the top-level
## SConstruct file

Import('env')

#obj=env.kobject('program', env)
#obj.target='test_fingering'
#obj.source='test_fingering.cpp'
#obj.includes='../../base ../../ ../../..'
#obj.libs='guitar kdeui base'
#obj.libpaths='../../base .'
#obj.execute()

#obj=env.kobject('program', env)
#obj.target='test_guitar'
#obj.source='test_guitar.cpp'
#obj.includes='../../base ../../ ../../..'
#obj.libs='guitar kdeui base'
#obj.libpaths='../../base .'
#obj.execute()

#obj=env.kobject('program', env)
#obj.target='test_note'
#obj.source='test_note.cpp'
#obj.includes='../../base ../../ ../../..'
#obj.libs='guitar kdeui base'
#obj.libpaths='../../base .'
#obj.execute()

#obj=env.kobject('program', env)
#obj.target='test_barre'
#obj.source='test_barre.cpp'
#obj.includes='../../base ../../ ../../..'
#obj.libs='guitar kdeui base'
#obj.libpaths='../../base .'
#obj.execute()

#obj=env.kobject('program', env)
#obj.target='test_chordmap'
#obj.source='test_chordmap.cpp'
#obj.includes='../../base ../../ ../../..'
#obj.libs='guitar kdeui base'
#obj.libpaths='../../base .'
#obj.execute()

#obj=env.kobject('program', env)
#obj.target='test_fingeringconstruct'
#obj.source='test_fingeringconstruct.cpp'
#obj.includes='../../base ../../ ../../..'
#obj.libs='guitar kdeui base'
#obj.libpaths='../../base .'
#obj.execute()

guitar_src="""
barre.cpp
barrelist.cpp
chord.cpp
chordmap.cpp
chordname.cpp
DuplicateException.cpp
fingering.cpp
fingers.cpp
guitar.cpp
guitarchordeditor.cpp
guitartabselector.cpp
guitarxmlhandler.cpp
note.cpp
symbols.cpp
"""

obj=env.kobject('staticlib', env)
obj.target='libguitar'
obj.source=guitar_src
obj.libpaths='../../base .'
obj.includes='../../base ../../ ../../..'
obj.libs='kdeui ../../base/libbase.a'
obj.execute()
