#!/bin/bash
#
# fix-links
#
# Copyright (c) 2004  D. Michael McIntyre <dmmcintyr@users.sourceforge.net>
# Released under the GPL
#
# HTMLDOC converts/exports to /tmp along with the images, changing all the
# paths to .  so we go in and sed them to change them back to ../pixmaps

# usage: fix-links [target directory] 

# NOTE: this approach is too simplistic to handle the situation if we end up
# with separate pixmaps by language in different directories, which is what
# should eventually happen if this thing is done right...  sigh...

error () {
    echo "Something went awry with $1...  Investigate."
    echo "Aborting..."
    exit 1
}

splinf=$RANDOM

for file in $1/*.html;do
#    sed s@SRC=\"@SRC=\"../pixmaps/@g $file > /tmp/$(basename $file)||exit 1
#    mv -f /tmp/$(basename $file) $file||exit 1

    # fix the broken pixmap path reset by HTMLDoc
    perl -i -p -e 's@SRC=\"@SRC=\"../pixmaps/@g' $file     || error "fixing links"

    # fix the broken links to an index.html that doesn't exist
    perl -i -p -e 's@index\.html@chapter-0\.html@g' $file  || error "fixing index files"

    # sed the HEIGHT and WIDTH tags out of the published web HTML
#    ../admin/strip-tags $file > /tmp/$splinf               || error "stripping tags (A)"
#    mv /tmp/$splinf $file                                  || error "stripping tags (B)"
	
done

exit 0
