#!/bin/bash
#
# fix-local-links
#
# Copyright (c) 2004  D. Michael McIntyre <dmmcintyr@users.sourceforge.net>
# Released under the GPL
#
# Part of "Silvan's Sysadmin Suite" of scripts for lazy people.
#
# REQUIRES: 

# OO does retarded things with local links.  Things like http://somefile.html
# need to be repaired

# this script is crappy, and really needs to use that Perl magic flummy and
# otherwise become much less crappy

echo this script is currently broken

exit 5

perl -i -p -e 's@http://chapter@chapter@g' chapter-2.html

REMEMBER: something is putting a html/ in...  probably fixlinks

Fix it when you get ack from work


for file in $1/*.html;do
    sed s@http://chapter@chapter@g $file > /tmp/$(basename $file)||exit 1
    mv -f /tmp/$(basename $file) $file||exit 1
done


for file in $1/*.html;do
    sed s@file:/home/silvan/CVS/tutorial/using-rosegarden/en/@../@g $file > /tmp/$(basename $file)||exit 1
    mv -f /tmp/$(basename $file) $file||exit 1
done

exit 0
