#!/bin/bash
#
# insert-chapter
#
# cheap utility to insert a chapter by incrementing file numbers and sedding
# them to attempt to update the headings
#
# D. Michael McIntyre <dmmcintyr@users.sourceforge.net>
#
#

for f in `ls *.html|sort -n`;do
    maxpos=$(echo $f|cut -d \- -f 2|cut -d \. -f1);
done

if ($# != 1); then
    echo "usage: insert-chapter [new number]"
    exit 0
fi

startpos=$1

echo inserting chapter $startpos...

for ((pos=maxpos;pos > startpos;pos--));do
    ((newpos=pos + 1))
    cat chapter-$pos.html|sed s/\"$pos/\"$newpos/g|sed s/\>$pos/\>$newpos/g > /tmp/blingbling-$pos
    echo moving chapter-$pos to chapter-$newpos and sedding the headers...
    mv -f /tmp/blingbling-$pos chapter-$newpos.html
done

echo done.

exit 0
