#!/bin/sh
tmpdir="release_tmp_$$"
version=`grep VERSION SConstruct|head -1|sed 's/^.*"\([^"]*\)" *$/\1/'|grep -v ' '`
if [ -z "$version" ]; then
	echo "ERROR: Failed to extract version number from SConstruct"
	exit 1
fi
mkdir "$tmpdir" || exit 1
cd "$tmpdir"
rgname="rosegarden-$version"
tarname="$rgname.tar.bz2"
echo "Building tarball for $rgname"
CVSROOT=`cat ../CVS/Root` cvs -z3 co -P rosegarden
mv rosegarden "$rgname"
tar cvjf "$tarname" "$rgname" --exclude=RGbuild --exclude=CVS --exclude=.svn --exclude=web --exclude=docs/test --exclude=admin || exit 1
cd ..
mv "$tmpdir/$tarname" .
rm -rf "$tmpdir"
echo "Done"
