#! /usr/bin/env python
# -*- python -*-
############################
## load the config

## use the environment set in the top-level
## SConstruct file

Import('env')

chord_files= env.Split("""
a_flat_major.xml
c_major.xml
g_sharp.xml
""")

env.KDEinstall('KDEDATA','/rosegarden/default_chords', chord_files)
env.KDEinstall('KDEDATA','/rosegarden/default_chords', 'guitar.dtd')
