#! /usr/bin/env python
# -*- python -*-
############################
## load the config

## use the environment set in the top-level
## SConstruct file

Import('env')

rgseqSources="""
mmappedcontrolblock.cpp
mmappedsegment.cpp
rosegardensequencer.cpp
main.cpp
sequencermapper.cpp
rosegardensequenceriface.skel
"""

obj=env.kobject('program')
obj.target='rosegardensequencer'
obj.source=rgseqSources
obj.includes='# #base #sound #gui'
obj.libs='RosegardenSequencer RosegardenSound base kdeui kdecore'
obj.libpaths='../base ../sound'
obj.execute()
