import glob
Import( "env KDEdoc" )
myenv=env.Copy()

## documentation to build
myenv.Meinproc( "index.docbook" )

myenv['APPNAME'] = 'rosegarden'
KDEdoc( 'en', 'index.cache.bz2', myenv )
KDEdoc( 'en', 'index.docbook', myenv )

for png in glob.glob("*.png"):
    KDEdoc( 'en', png, myenv )

