#!/bin/bash
#
# startrg
#
# D. Michael McIntyre <dmmcintyr@users.sourceforge.net>
#
# This script is a convenient way to start Rosegarden with the output from
# iiwusynth and jackd in separate xterms, and the KDE_DEBUG environment
# variable set so that KDE's crash handler is disabled.  Of course your needs
# and requirements will vary, and this script in present form isn't very
# flexible.  You'll need to edit the USER VARIABLES below to configure its
# execution, and possibly edit the guts of the script itself.
#
# NOTE: I couldn't pass a command with parameters to xterm.  I'm sure there's
# a way, but for the time being I just threw jack and iiwusynth into separate
# start scripts.  Works...

# USER VARIABLES
#
# TOGGLES

start_jack=true
start_iiwusynth=false #doesn't seem to play nice with jack
log_to_xterm=true

#
# COMMAND USED TO START THE JACK SERVER
jack_command="startjack"  # separate script -- please edit


# COMMAND USED TO START IIWUSYNTH
ii_command="startsynth"   # separate script -- please edit

#
# FONT TO USE FOR XTERM (USE xfontsel TO GENERATE THE STRING)
font="*-fixed-*-*-20-*-*-*-*-*-*-*"

#
# Used to log program output to a dedicated Xterm
#
Xterm () {
    echo Starting xterm with parms $1 $2 $3
    /usr/X11R6/bin/xterm -fn "$1"                     \
        -geometry 80x25 -w 1 -T "$2"                  \
        +ah -bc -b 0 -pc -cn +mb -mesg +sb +sf +vb  \
                -fg white -bg black -e "$3"   &
}

Wait () {
    printf "Waiting on $1 to come up..."
    until (pgrep $1 > /dev/null 2>&1); do
        printf "."
        sleep 1
    done
    echo
}
                
# Disable the KDE crash handler
export KDE_DEBUG=1

# Start jackd
if [ "$start_jack" == "true" ]; then
    echo Starting jackd...
    if [ "$log_to_xterm" == "true" ]; then
        echo starting xterm
        Xterm $font "jackd status" $jack_command
        echo xterm finished
    else
        $jack_command > /dev/null 2>&1 &
    fi
    Wait jackd
else
    echo Skipping jackd...
fi

# Start IIWU Synth
if [ "$start_iiwusynth" == "true" ]; then
    echo Starting iiwusynth...
    if [ "$log_to_xterm" == "true" ]; then
        Xterm $font "iiwusynth status" $ii_command
    else
        $ii_command > /dev/null 2>&1  &
    fi
    Wait iiwusynth
else
    echo Skipping iiwusynth...
fi

# Start Rosegarden
echo Starting Rosegarden...
if [ "$log_to_xterm" == "true" ]; then
    Xterm $font "rosegarden status" rosegarden
else
    rosegarden &
fi
