#! /usr/bin/env python

Import ('env')

# examples
examples="""
glazunov.rg
notation-for-string-orchestra-in-D-minor.rg
ravel-pc-gmaj-adagio.rg
perfect-moment.rg
bogus-surf-jam.rg
the-rose-garden.rg
children.rg
stormy-riders.rg
Djer-Fire.rg"""

env.KDEinstall('KDEDATA','/rosegarden/examples', examples)

# autoload.rg
env.KDEinstall('KDEDATA', '/rosegarden', "autoload.rg")

