/* THIS FILE WAS GENERATED BY scripts/generate_exception_strings
 *
 * DO NOT EDIT THIS FILE.
 * 
 * This file contains extracted exception strings and places them into the
 * QObject::tr() context for translation.  This is less complicated than
 * accomplishing the job by throwing around a bunch of Q_DECLARE_TR_FUNCTIONS or
 * whatever macros in the right bits of code, and wrapping all those calls in
 * QObject::tr() functions.  Instead, we'll wrap anything that ever presents an
 * exception to the user, which will require less coding to get the job done.
 *
 * This file is under version control because it is not expected to change
 * regularly enough to justify building automatic updates into the build system,
 * and because the script that generated it depends on an uncommon utility
 * whose inclusion would mean adding a new build dependency over something quite
 * trivial.
 */

/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("track id already present");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("track id not found");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Value of ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad SysEx encoding");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("No data found for property ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad type for ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("No data found for property ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad type for ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Not an insert action");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("No GUI found");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Failed to start GUI");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Can't deal with relative .soname");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("No GUI subdir available");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Failed to connect to LIRC");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Failed reading LIRC config file");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Failed to open tranzport device /dev/tranzport0");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("could not map current mode to string.");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Cancelled");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad sound file ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad audio file path ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad audio file path (malformed file?) ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad peak file ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad peak file (malformed audio?) ");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Rosegarden currently only supports 8-, 16- or 24-bit PCM in RIFF files");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Rosegarden currently only supports 32-bit floating-point in RIFF files");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Wrong length for long data in MIDI stream");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Wrong length for int data in MIDI stream");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("End of MIDI file encountered while reading");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Attempt to get more bytes than expected on Track");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Attempt to read past MIDI file end");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("End of MIDI file encountered while reading");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Attempt to get more bytes than expected on Track");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Attempt to read past MIDI file end");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Invalid event code found");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Running status used for first event in track");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Not an insert action");


/* TRANSLATOR: this is an internal error string that will typically be included
 * as part of some error dialog reporting the nature of the failure to the
 * user. */
QObject::tr("Bad sound file");

