#! /usr/bin/env python
# -*- python -*-
############################
## load the config

## use the environment set in the top-level
## SConstruct file

Import('env')

base_src="""
AnalysisTypes.C
AudioDevice.C
AudioLevel.C
AudioPluginInstance.C
BaseProperties.C
Clipboard.C
Colour.C
ColourMap.C
Composition.C
CompositionTimeSliceAdapter.C
Configuration.C
ControlParameter.C
Device.C
Equation.C
Event.C
Exception.C
Instrument.C
LayoutEngine.C
Marker.C
MidiDevice.C
MidiProgram.C
MidiTypes.C
NotationTypes.C
Profiler.C
Property.C
PropertyMap.C
PropertyName.C
Quantizer.C
RealTime.C
RulerScale.C
Segment.C
SegmentMatrixHelper.C
SegmentNotationHelper.C
SegmentPerformanceHelper.C
Selection.C
Sets.C
SnapGrid.C
SoftSynthDevice.C
Staff.C
Studio.C
Track.C
TriggerSegment.C
ViewElement.C
XmlExportable.C
""".split()

obj=env.genobj('staticlib',env)
obj.libpaths='./ ../'
obj.includes='# ../gui'
obj.target='libbase'
obj.src=base_src
obj.execute()



# TODO remove
"""
myenv['LIBPATH'].append('.')
myenv['LIBPATH'].append('..')
base = myenv.Library('base', base_src)
Default(base)
"""

