# Find the msgfmt executable
#
# It will set the following variables:
#  MSGFMT_FOUND
#  MSGFMT_EXECUTABLE
#

IF (MSGFMT_EXECUTABLE)
    SET(MSGFMT_FOUND TRUE)
ELSE (MSGFMT_EXECUTABLE)
    FIND_PROGRAM(MSGFMT_EXECUTABLE
        NAMES msgfmt
        PATHS /bin /usr/bin /usr/local/bin )
    IF(MSGFMT_EXECUTABLE)
        SET(MSGFMT_FOUND TRUE)
    ELSE(MSGFMT_EXECUTABLE)
    	IF(MSGFMT_FIND_REQUIRED)
            MESSAGE(FATAL_ERROR "Could not find msgfmt program.")
        ENDIF(MSGFMT_FIND_REQUIRED)
    ENDIF(MSGFMT_EXECUTABLE)
    MARK_AS_ADVANCED(MSGFMT_EXECUTABLE)
ENDIF (MSGFMT_EXECUTABLE)
