# - Try to find FFTW3F
# Once done this will define:
#
#  FFTW3F_FOUND - system has FFTW3F
#  FFTW3F_LIBRARY - FFTW3F library
#  FFTW3F_LIBS - FFTW3F link flags
#  FFTW3F_INC_DIR - FFTW3F include dir

SET(CMAKE_INCLUDE_PATH ".")
INCLUDE(PkgConfigV)

PKGCONFIGV(fftw3f 3.0.0 _FFTW3FVersion _FFTW3FIncDir _FFTW3FLinkDir _FFTW3FLinkFlags _FFTW3FCflags)

SET(FFTW3F_CFLAGS ${_FFTW3FCflags})
SET(FFTW3F_INC_DIR ${_FFTW3FIncDir})
SET(FFTW3F_VERSION ${_FFTW3FVersion})
SET(FFTW3F_LIBS ${_FFTW3FLinkFlags})
SET(FFTW3F_LIB_DIR ${_FFTW3FLinkDir})

IF(FFTW3F_VERSION)
    SET(FFTW3F_FOUND TRUE)
ENDIF(FFTW3F_VERSION)

IF(NOT FFTW3F_FOUND)
    IF(FFTW3F_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find fftw3f")
    ENDIF(FFTW3F_FIND_REQUIRED)
ENDIF(NOT FFTW3F_FOUND)

MARK_AS_ADVANCED(FFTW3F_CFLAGS)
