# - Try to find LADSPA header
# Once done this will define:
#
#  LADSPA_FOUND - system has LADSPA
#  LADSPA_INC_DIR - LADSPA header path

IF(LADSPA_INC_DIR)
    SET(LADSPA_FOUND TRUE)
ELSE(LADSPA_INC_DIR)
    INCLUDE(CheckIncludeFile)
    SET(LADSPA_FOUND FALSE)
    SET(LADSPA_INC_DIR)
    CHECK_INCLUDE_FILE("ladspa.h" HAVE_LADSPA_H)
    IF(HAVE_LADSPA_H)
        FIND_PATH(LADSPA_INC_DIR "ladspa.h") 
        SET(LADSPA_FOUND TRUE)
    ENDIF(HAVE_LADSPA_H)
ENDIF(LADSPA_INC_DIR)
