# - Try to find LRDF
# Once done this will define:
#
#  LRDF_FOUND - system has LRDF
#  LRDF_LIBRARY - LRDF library
#  LRDF_LIBS - LRDF link flags
#  LRDF_INC_DIR - LRDF include dir

INCLUDE (CheckIncludeFile)
INCLUDE (CheckLibraryExists)

CHECK_INCLUDE_FILE("lrdf.h" HAVE_LRDF_H)
IF(HAVE_LRDF_H)
	CHECK_LIBRARY_EXISTS(lrdf lrdf_init "" HAVE_LRDF_INIT)
	IF(HAVE_LRDF_INIT)
		SET(LRDF_LIBS "-llrdf")
		FIND_PATH(LRDF_INC_DIR "lrdf.h" "")
		FIND_LIBRARY(LRDF_LIBRARY NAME lrdf PATHS "")
		IF(LRDF_INC_DIR AND LRDF_LIBRARY)
			SET(LRDF_FOUND TRUE)
		ENDIF(LRDF_INC_DIR AND LRDF_LIBRARY)
	ENDIF(HAVE_LRDF_INIT)
ENDIF(HAVE_LRDF_H)

MARK_AS_ADVANCED(LRDF_LIBRARY LRDF_LIBS)
