# - Try to find XFT 2.1.0
# Once done this will define:
#
#  XFT_FOUND - system has XFT
#  XFT_LIBRARY - XFT library name
#  XFT_CFLAGS - Compiler switches required for using XFT
#  XFT_LIBS - Linker flags
#  XFT_LIB_DIR - Library directory
#  XFT_INC_DIR - Include diretory
#  XFT_VERSION - XFT version found

SET(CMAKE_INCLUDE_PATH ".")
INCLUDE(PkgConfigV)

PKGCONFIGV(xft 2.1.0 _XFTVersion _XFTIncDir _XFTLinkDir _XFTLinkFlags _XFTCflags)

SET(XFT_CFLAGS ${_XFTCflags})
SET(XFT_LIBS ${_XFTLinkFlags})
SET(XFT_LIB_DIR ${_XFTLinkDir})
SET(XFT_INC_DIR ${_XFTIncDir})
SET(XFT_VERSION ${_XFTVersion})

EXEC_PROGRAM(${PKGCONFIG_EXECUTABLE} ARGS xft --cflags-only-I OUTPUT_VARIABLE AUX_FLAGS )
STRING(REPLACE "-I" "" AUX_FLAGS ${AUX_FLAGS})
SEPARATE_ARGUMENTS(AUX_FLAGS)
SET(XFT_INC_DIR ${XFT_INC_DIR} ${AUX_FLAGS})
SEPARATE_ARGUMENTS(XFT_LIBS)

FIND_LIBRARY(XFT_LIBRARY
  NAMES Xft
  PATHS ${_XFTLinkDir}
)

IF(XFT_LIBRARY)
    SET(XFT_FOUND TRUE)
ENDIF(XFT_LIBRARY)

IF(NOT XFT_FOUND)
    IF(XFT_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find XFT >= 2.1.0")
    ENDIF(XFT_FIND_REQUIRED)
ENDIF(NOT XFT_FOUND)

MARK_AS_ADVANCED(XFT_LIBRARY XFT_CFLAGS XFT_LIBS)
